# Generated by Django 4.2.7 on 2023-11-21 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brodacastMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('players', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('accepted_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), null=True, size=None)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='favSports',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('sport', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SportList',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
