# Generated by Django 4.2.7 on 2023-11-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0002_brodacastmessages_favsports_sportlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brodacastmessages',
            name='players',
            field=models.IntegerField(),
        ),
    ]
